import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { AuthProvider } from "@/context/AuthContext"; // Hier den AuthProvider importieren
import ToastContainerComponent from "./components/ToastContainerComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "ToDo-APP",
  description: "Generated by create next app",
  author: "akocerke",
};

export default function RootLayout({ children }) {
  return (
    <html lang="de" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AuthProvider> {/* AuthProvider hier einfügen */}
          <Navbar />
          <ToastContainerComponent/>
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
